apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: e2e-test3
  namespace: default
spec:
  components:
        
          - name: e2e-test3
            type: webservice
            properties:
              name: e2e-test3
              image: healthidpuaeacr.azurecr.io/e2e-test3:latest
              language: python
              framework: fastapi
              port: 8080
              healthPath: /health
              appContainer: e2e-test3
              exposeApi: true
